/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as genesisNft from "./GenesisNFT";
export type { genesisNft };
export type { Coolpo } from "./Coolpo";
export type { Cybergirl } from "./Cybergirl";
export type { Max } from "./Max";
export type { MaxComponents } from "./MaxComponents";
export type { Thomas } from "./Thomas";
