/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessories from "./Accessories";
export type { accessories };
export type { Genesis } from "./Genesis";
