/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as genesisNft from "./GenesisNFT";
export type { genesisNft };
import type * as nfTs from "./NFTs";
export type { nfTs };
import type * as vesting from "./vesting";
export type { vesting };
export type { PopToken } from "./PopToken";
