/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TokenSaleDistributor } from "./TokenSaleDistributor";
export type { TokenSaleDistributorProxy } from "./TokenSaleDistributorProxy";
export type { TokenSaleDistributorProxyStorage } from "./TokenSaleDistributorProxyStorage";
export type { TokenSaleDistributorStorage } from "./TokenSaleDistributorStorage";
