/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessories from "./Accessories";
export type { accessories };
import type * as accessoriesSol from "./Accessories.sol";
export type { accessoriesSol };
export type { Genesis } from "./Genesis";
